### ISSUE TITLE
Issues with UMD, automatically generate UMD

### ISSUE THREAD

**Issue by Hypercubed** [azaslavsky/domJSON#20]
You have a typo in the UMD script here (`dmoJSON` should be `domJSON`): https://github.com/azaslavsky/domJSON/blob/master/src/domJSON.js#L24

Also, in CJS `this` is not `window` so the script fails here `win.location` is undefined):  https://github.com/azaslavsky/domJSON/blob/master/src/domJSON.js#L55

I can easily submit a PR for these but I think it might be better if you wrote the code as CJS then ran it through browsify to get UMD.  If you are interested I can submit a PR.

**Comment by azaslavsky** [comment]
A PR to get started on would be great.  And yes, that typo should be fixed :)

**Comment by Hypercubed** [comment]
I made progress on this (see here: https://github.com/Hypercubed/domJSON/tree/refactor/build).  I converted the source to CJS then using browserify (see `package.json scripts`) to convert to UMD.  Personally, these days, I prefer to use npm scripts to do the simple build steps (like browserify and uglify).  However, it is easy enough to add browserify as a gulp step (see https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md). 

I'm having some trouble with your building and testing setup.  Your karma setup requires testing the UMD code which means you need to run tests after the conversion to UMD, but before your `test-code` is removed.  You can handle this a few ways... generating a temp UMD source for testing, put tests in-between browserify and `gulp build`, or otherwise refactor your tests.  I'm not sure what approach you would like to take for this.

**Comment by azaslavsky** [comment]
Sorry, very pressed at work this week.  I'll try and resolve this issue over the weekend.

**Comment by azaslavsky** [comment]
Solved by #31

**Comment by ramakrishnamundru** [comment]
@azaslavsky Sorry for digging up an old issue. Can you please rebuild and publish a new version to npm. We are unable to test our application because of this error.
