### ISSUE TITLE
Getting the complete DOM

### ISSUE THREAD

**Issue by lolaclinton** [azaslavsky/domJSON#21]
Hi,
I was wondering how I can get the full DOM for a page. I tried putting in the html element or the body element but it crashed on them both.
Thanks

**Comment by lolaclinton** [comment]
I gave it the document.body, from the home page of the mcdonalds.com website which seemed okay, but I got the following error
_org.openqa.selenium.ElementNotVisibleException: element not visible: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('email') does not support selection._
Does that mean the elements need to be visible to be read? Is there a way around it?

**Comment by azaslavsky** [comment]
Hmm, I am 90% sure this is the same issue as the one here: https://github.com/azaslavsky/domJSON/issues/18.  I'm very slammed at work right now, but I will try and look at this as soon as I have a moment.

**Comment by ssnet-xyz** [comment]
Hmm, for me it crashes on inputs of type submit and button, visible or not. (Love this tool by the way!)

**Comment by azaslavsky** [comment]
This issue should be resolved by commit #32
