### ISSUE TITLE
Help guide has the wrong implementation of Node.replaceChild()

### ISSUE THREAD

**Issue by ZachRHale** [azaslavsky/domJSON#25]
This took me a second to realize while using the plugin.

https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild

Instead of 

`var DOMDocumentFragment = domJSON.toDOM(jsonOutput);
someDOMElement.parentNode.replaceChild(someDOMElement, DOMDocumentFragment);`

it should be 

`var DOMDocumentFragment = domJSON.toDOM(jsonOutput);
someDOMElement.parentNode.replaceChild(DOMDocumentFragment, someDOMElement);`

at least in Chrome/60.0.3112.113 in the console

**Comment by azaslavsky** [comment]
Good eye!  Fixed.
