### ISSUE TITLE
I do not get instructions

### ISSUE THREAD

**Issue by Cookiewookie87** [azaslavsky/domJSON#35]
Under usage there is:
`var someDOMElement = document.getElementById('sampleId');
var jsonOutput = domJSON.toJSON(myDiv);`

first we select ID, than there is some myDiv...i am confused. Can you be more specific or descriptive? Beginner here

**Comment by KaiTang26** [comment]
I got confused as well. did you find out?

**Comment by Cookiewookie87** [comment]
No :/ but i would be happy if author would help

**Comment by azaslavsky** [comment]
The docs have been updated.  "myDiv" should have been someDOMElement, it was a typo.
